# Configuration for compression of Salt Cove network.
# Restrict to values of interest.

[solid_constants]
dilation_angle = 0.1 # radians

[geometry]
domain_size = 1000.0   # meters
cell_size = 30.0       # meters
cell_size_fracture = 1 # meters

[bc]
background_stress = [-2e6, -2e7]

[numerics]
characteristic_contact_traction = 1e7 # Pa

[contact]
#normal_formulation = "alart_curnier"
#tangential_formulation = "alart_curnier"

#normal_formulation = "alart_curnier"
#tangential_formulation = "hueber"

normal_formulation = "bipotential_orthogonal_return"
tangential_formulation = "bipotential_orthogonal_return"

#normal_formulation = "ncp_min"
#tangential_formulation = "ncp_min"

#normal_formulation = "ncp_fb"
#tangential_formulation = "ncp_fb"
